name: pg

# 触发条件
on:
  schedule:
    # 
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write # 确保 GITHUB_TOKEN 具有写入权限

env:
  TZ: Asia/Shanghai # 设置时区为北京时间

jobs:
  Update:
    runs-on: ubuntu-latest

    steps:
    # 检出项目仓库
    - name: Checkout repository
      uses: actions/checkout@v4

    # 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v5

    # 安装依赖
    - name: Install dependencies
      run: if [ -f .github/requirements.txt ]; then pip install -r .github/requirements.txt; fi

    # 运行 Python 脚本
    - name: Run script
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        python py/sync-pg.py
