name: Auto Process Zip Files

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间00:00运行
  workflow_dispatch:     # 允许手动触发

jobs:
  process-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        repository: username/target-repo
        token: ${{ secrets.GIT_TOKEN }}
        path: target-repo

    - name: Clone source repo
      env:
        GITHUB: ${{ secrets.GITHUB }}
      run: |
        git clone {GITHUB} source-repo

    - name: Find and process zip files
      run: |
        cd source-repo
        ZIP_FILE=$(find . -type f -name "pg\.(\d{8})-(\d{4})\.zip" | head -n 1)
        
        if [ -z "$ZIP_FILE" ]; then
          echo "No zip file found"
          exit 0
        fi

        unzip -o "$ZIP_FILE" -d ../target-repo/
        rm -rf ../target-repo/__MACOSX  # 清理macOS生成的垃圾文件

    - name: Commit and push changes
      run: |
        cd target-repo
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        git add .
        git commit -m "Auto update from source repo" || echo "No changes to commit"
        git push origin main